export const banks = [
  { value: "kcb", label: "KCB Bank Kenya" },
  { value: "equity", label: "Equity Bank Kenya" },
  { value: "cooperative", label: "Co-operative Bank of Kenya" },
  { value: "ncba", label: "NCBA Bank Kenya" },
  { value: "absa", label: "Absa Bank Kenya" },
  { value: "standard-chartered", label: "Standard Chartered Bank Kenya" },
  { value: "stanbic", label: "Stanbic Bank Kenya" },
  { value: "im", label: "I&M Bank Kenya" },
  { value: "dtb", label: "Diamond Trust Bank (DTB)" },
  { value: "boa", label: "Bank of Africa Kenya" },
  { value: "family", label: "Family Bank" },
  { value: "sbm", label: "SBM Bank Kenya" },
  { value: "prime", label: "Prime Bank" },
  { value: "paramount", label: "Paramount Bank" },

  { value: "access", label: "Access Bank Kenya" },
  { value: "abc", label: "African Banking Corporation (ABC Bank)" },
  { value: "citibank", label: "Citibank Kenya" },
  { value: "consolidated", label: "Consolidated Bank of Kenya" },
  { value: "credit-bank", label: "Credit Bank" },
  { value: "development-bank", label: "Development Bank of Kenya" },
  { value: "dib", label: "DIB Bank Kenya" },
  { value: "ecobank", label: "Ecobank Kenya" },
  { value: "gtbank", label: "Guaranty Trust Bank Kenya" },
  { value: "gulf-african", label: "Gulf African Bank" },
  { value: "habib-zurich", label: "Habib Bank AG Zurich" },
  { value: "housing-finance", label: "Housing Finance Bank (HF Group)" },
  { value: "kingdom", label: "Kingdom Bank" },
  { value: "middle-east", label: "Middle East Bank Kenya" },
  { value: "moriental", label: "M Oriental Bank" },
  { value: "nbk", label: "National Bank of Kenya" },
  { value: "sidian", label: "Sidian Bank" },
  { value: "victoria", label: "Victoria Commercial Bank" },
  { value: "uba", label: "United Bank for Africa (UBA Kenya)" },
];